### ISSUE TITLE
ERROR: Layer qt5-layer is not compatible

### ISSUE THREAD

**Issue by elhawaryna** [satdreamgr/oe-core#11]
`Hallo
Possible help to build
Thank you so much
--------------------------------ERROR-------------------------
`elhawary@elhawary-MS-7848:~/oe-core$ MACHINE=dm820 make image
Building image for dm820
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/elhawary/oe-core/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 3018383 at 2021-02-14 10:29:00.491098 ---
ERROR: Layer qt5-layer is not compatible with the core layer which only supports these series: zeus (layer is compatible with sumo rocko)

make: *** [Makefile:117: image] Error 1
elhawary@elhawary-MS-7848:~/oe-core$

**Comment by athoik** [comment]
You need to modify conf/layer.conf and  set LAYERSERIES_COMPAT_qt5-layer = "rocko sumo zeus"
