### ISSUE TITLE
ERROR: streamlink-Help, please 

### ISSUE THREAD

**Issue by elhawaryna** [satdreamgr/oe-core#13]
Help, please 
`ERROR: streamlink-2.0.0+gitAUTOINC+4df7ea873c-r0 do_populate_lic: QA Issue: streamlink: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=6e2f7fbdd7536a59eed68a6b8e99dbf7
streamlink: The new md5 checksum is 7c0be52291b7252b878da806d185b1d1
streamlink: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Copyright (c) 2011-2016, Christopher Rosell
Copyright (c) 2016-2021, Streamlink Team
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
...
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
streamlink: Check if the license information has changed in /home/elhawary/oe-core/build/tmp/work/mips32el-oe-linux/streamlink/2.0.0+gitAUTOINC+4df7ea873c-r0/git/LICENSE to verify that the LICENSE value "BSD" remains valid [license-checksum]
ERROR: streamlink-2.0.0+gitAUTOINC+4df7ea873c-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/oe-core/build/tmp/work/mips32el-oe-linux/streamlink/2.0.0+gitAUTOINC+4df7ea873c-r0/temp/log.do_populate_lic.3574994
ERROR: Task (/home/elhawary/oe-core/meta-satdreamgr/recipes-devtools/python/streamlink.bb:do_populate_lic) failed with exit code '1'`

**Comment by elhawaryna** [comment]
https://www.mediafire.com/file/daerfkxutmutsvb/console-latest.zip/file

**Comment by athoik** [comment]
Update to HEAD, checksum fixed.
