### ISSUE TITLE
Error in Applying patch 0001-Set-default-skin-Satdreamgr-HD-TranspBA.patch

### ISSUE THREAD

**Issue by islamsabry2008** [satdreamgr/oe-core#14]
I have this error
`ERROR: enigma2-2.7+gitAUTOINC+4edd168947-r0 do_patch: Command Error: 'quilt --quiltrc /home/islam/oe-core/build/tmp/work/h9combo-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+4edd168947-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-Set-default-skin-Satdreamgr-HD-TranspBA.patch
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/skin.py b/skin.py
|index 86f41087e6..49a9111fc0 100644
|--- a/skin.py
|+++ b/skin.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch 0001-Set-default-skin-Satdreamgr-HD-TranspBA.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /home/islam/oe-core/build/tmp/work/h9combo-oe-linux-gnueabi/enigma2/2.7+gitAUTOINC+4edd168947-r0/temp/log.do_patch.4225
ERROR: Task (/home/islam/oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch) failed with exit code '1'`

**Comment by athoik** [comment]
Should be fixed on https://github.com/satdreamgr/oe-core/commit/2eaabe7aa4660fb16c9364bd82822c8c4935cb6e#diff-3eb6dea4c9a8eb800534cfd07425819639239a5d622726527c30079a49c0b27a
